#include "kernel/object/authority_validation_contract.h"

int main(void) {
    os_authority_validation_stage_t stage =
        OS_AUTHORITY_VALIDATION_STAGE_HANDLE_TABLE_OWNERSHIP;

    os_authority_validation_stage_t stages[] = {
        OS_AUTHORITY_VALIDATION_STAGE_HANDLE_TABLE_OWNERSHIP,
        OS_AUTHORITY_VALIDATION_STAGE_HANDLE_VALIDITY,
        OS_AUTHORITY_VALIDATION_STAGE_OBJECT_TYPE_COMPATIBILITY,
        OS_AUTHORITY_VALIDATION_STAGE_OBJECT_LIVENESS,
        OS_AUTHORITY_VALIDATION_STAGE_REQUIRED_RIGHTS,
        OS_AUTHORITY_VALIDATION_STAGE_OPERATION_PRECONDITIONS,
    };

    os_status_t statuses[] = {
        OS_AUTHORITY_VALIDATION_STATUS_HANDLE_TABLE_OWNERSHIP,
        OS_AUTHORITY_VALIDATION_STATUS_HANDLE_VALIDITY,
        OS_AUTHORITY_VALIDATION_STATUS_OBJECT_TYPE_COMPATIBILITY,
        OS_AUTHORITY_VALIDATION_STATUS_OBJECT_LIVENESS,
        OS_AUTHORITY_VALIDATION_STATUS_REQUIRED_RIGHTS,
        OS_AUTHORITY_VALIDATION_STATUS_OPERATION_PRECONDITIONS,
    };

    os_authority_validation_stage_status_map_t mapping = {
        .stage = OS_AUTHORITY_VALIDATION_STAGE_REQUIRED_RIGHTS,
        .status = OS_AUTHORITY_VALIDATION_STATUS_REQUIRED_RIGHTS,
    };

    return (int)(stage + stages[0] + statuses[0] + mapping.stage + mapping.status);
}
